# Dockerfile.migrate
FROM golang:1.24.9

WORKDIR /app
COPY .. /app

RUN go install github.com/pressly/goose/v3/cmd/goose@v3.26.0

ENTRYPOINT ["sh", "-c"]
CMD ["goose -dir ./migrations postgres \"postgres://postgres:1234@db:5432/dental_clinic?sslmode=disable\" up"]
